name: Build and release APKs

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out main
        uses: actions/checkout@v7
        with:
          ref: main

      - name: Set up Java
        uses: actions/setup-java@v6
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew assembleRelease --stacktrace

      - name: Move and rename APKs
        run: |
          mv app/build/outputs/apk/release/app-release.apk adbsms.apk
          mv min/build/outputs/apk/release/min-release.apk adbsms.min.apk

      - name: Generate checksums
        run: |
          sha256sum adbsms.apk >> checksums.txt
          sha256sum adbsms.min.apk >> checksums.txt

      - name: Generate short hash
        id: short-hash
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            adbsms.apk
            adbsms.min.apk
            checksums.txt
          body: |
            Automated build: ${{ steps.short-hash.outputs.hash }}
            
            ${{ github.event.head_commit.message }}